export const wilayas: Record<string, string[]> = {
  "Adrar": ["Adrar", "Reggane", "Zaouiet Kounta", "Aoulef", "Fenoughil", "Timentit", "Timimoun", "Charouine"],
  "Chlef": ["Chlef", "Tenes", "El Karimia", "Ouled Fares", "Oued Fodda", "Beni Haoua", "Abou El Hassane"],
  "Laghouat": ["Laghouat", "Aflou", "Ksar El Hirane", "Brida", "Sidi Makhlouf"],
  "Oum El Bouaghi": ["Oum El Bouaghi", "Ain Beida", "Ain M'lila", "Meskiana", "Souk Naamane"],
  "Batna": ["Batna", "Tazoult", "Merouana", "Arris", "N'gaous", "Barika"],
  "Bejaia": ["Bejaia", "Akbou", "Amizour", "Tichy", "Seddouk", "El Kseur"],
  "Biskra": ["Biskra", "Tolga", "Ouled Djellal", "Zeribet El Oued", "El Kantara"],
  "Bechar": ["Bechar", "Kenadsa", "Abadla", "Taghit", "Beni Ounif"],
  "Blida": ["Blida", "Boufarik", "El Affroun", "Mouzaia", "Oued El Alleug"],
  "Bouira": ["Bouira", "Sour El Ghozlane", "Lakhdaria", "M'Chedallah", "El Hachimia"],
  "Tamanrasset": ["Tamanrasset", "Abalessa", "In Salah", "In Guezzam"],
  "Tebessa": ["Tebessa", "El Kouif", "Bir El Ater", "Cheria", "Negrine"],
  "Tlemcen": ["Tlemcen", "Maghnia", "Ghazaouet", "Remchi", "Nedroma", "Sebdou"],
  "Tiaret": ["Tiaret", "Frenda", "Mahdia", "Sougueur", "Rahouia"],
  "Tizi Ouzou": ["Tizi Ouzou", "Azazga", "Draa Ben Khedda", "Ouaguenoun", "Azeffoun"],
  "Alger": ["Bab El Oued", "El Harrach", "Bir Mourad Rais", "Dar El Beida", "Hussein Dey"],
  "Djelfa": ["Djelfa", "Ain Oussera", "Messaad", "El Idrissia", "Dar Chioukh"],
  "Jijel": ["Jijel", "Taher", "El Milia", "Texenna", "Settara"],
  "Setif": ["Setif", "El Eulma", "Ain Oulmene", "Bougaa", "Beni Aziz"],
  "Saida": ["Saida", "Ouled Brahim", "Ain El Hadjar", "Youb"],
  "Skikda": ["Skikda", "Collo", "Azzaba", "El Harrouch", "Ben Azzouz"],
  "Sidi Bel Abbes": ["Sidi Bel Abbes", "Telagh", "Merine", "Mostefa Ben Brahim"],
  "Annaba": ["Annaba", "El Hadjar", "Berrahal", "Ain El Berda"],
  "Guelma": ["Guelma", "Oued Zenati", "Bouati Mahmoud", "Hammam Debagh"],
  "Constantine": ["Constantine", "El Khroub", "Didouche Mourad", "Zighoud Youcef", "Ain Abid"],
  "Medea": ["Medea", "Berrouaghia", "Tablat", "Ksar El Boukhari", "Ouled Antar"],
  "Mostaganem": ["Mostaganem", "Ain Tedles", "Sidi Lakhdar", "Mesra"],
  "M'Sila": ["M'Sila", "Bousaada", "Sidi Aissa", "Chelghoum Laid"],
  "Mascara": ["Mascara", "Sig", "Tighennif", "Oued El Abtal"],
  "Ouargla": ["Ouargla", "Hassi Messaoud", "Touggourt", "Taibet"],
  "Oran": ["Oran", "Es Senia", "Bir El Djir", "Aïn El Turk", "Arzew", "Boutlelis"],
  "El Bayadh": ["El Bayadh", "Boualem", "Chellala", "Rogassa"],
  "Illizi": ["Illizi", "Djanet", "In Amenas"],
  "Bordj Bou Arreridj": ["Bordj Bou Arreridj", "El Achir", "Mansoura", "Medjana"],
  "Boumerdes": ["Boumerdes", "Bordj Menaiel", "Thenia", "Dellys"],
  "El Tarf": ["El Tarf", "Bouhadjar", "Besbes", "Drean"],
  "Tindouf": ["Tindouf"],
  "Tissemsilt": ["Tissemsilt", "Bordj Bounaama", "Theniet El Had"],
  "El Oued": ["El Oued", "Debila", "Reguiba", "Guemar"],
  "Khenchela": ["Khenchela", "Ain Touila", "Chelia", "Kais"],
  "Souk Ahras": ["Souk Ahras", "Sedrata", "Mechroha", "Taoura"],
  "Tipaza": ["Tipaza", "Cherchell", "Hadjout", "Bou Ismail"],
  "Mila": ["Mila", "Chelghoum Laid", "Telerghma", "Ferdjioua"],
  "Ain Defla": ["Ain Defla", "Miliana", "El Attaf", "Rouina"],
  "Naama": ["Naama", "Mecheria", "Ain Sefra", "Moghrar"],
  "Ain Temouchent": ["Ain Temouchent", "Hammam Bouhadjar", "El Malah", "Ain El Arbaa"],
  "Ghardaia": ["Ghardaia", "Berriane", "Metlili", "Zelfana"],
  "Relizane": ["Relizane", "Yellel", "Mazouna", "Oued Rhiou"],
  "Timimoun": ["Timimoun", "Ouled Said", "Aougrout"],
  "Bordj Badji Mokhtar": ["Bordj Badji Mokhtar"],
  "Ouled Djellal": ["Ouled Djellal", "Ras El Miad"],
  "Béni Abbès": ["Beni Abbes", "Igli", "Kerzaz"],
  "In Salah": ["In Salah", "In Ghar"],
  "In Guezzam": ["In Guezzam"],
  "Touggourt": ["Touggourt", "Megarine", "Nezla"],
  "Djanet": ["Djanet"],
  "El M'Ghair": ["El M'Ghair", "Djamaa"],
  "El Meniaa": ["El Meniaa"],
};
