export const wilayas: Record<string, string[]> = {
  "Adrar": ["Aoulf", "Adrar", "Fnoughil", "Zaouia Knta", "Rkan", "Tsabit"],
  "Alchlf": ["Abou Alhsn", "Alzboudja", "Aoulad Bn Abd Alkadr", "Ain Mran", "Bni Houa", "Ouadi Alfda", "Almrsa", "Alchlf", "Tns", "Alkrimia", "Taoukrit", "Aoulad Fars", "Boukadir"],
  "Laghouat": ["Ktla Sidi Said", "Brida", "Ain Madi", "Alghicha", "Aflou", "Ouadi Mra", "Alaghouat", "Ksr Alhiran", "Sidi Mkhlouf", "Hasi Alrml"],
  "Oum El Bouaghi": ["Fkirina", "Ain Fkroun", "Mskiana", "Ksr Alsbahi", "Souk Naman", "Am Albouaki", "Ain Bbouch", "Ain Albida", "Ain Mlila", "Sikous", "Aldlaa", "Ain Krcha"],
  "Batna": ["Ain Altouta", "Ras Alaioun", "Timkad", "Aoulad Si Sliman", "Thnia Alaabd", "Batna", "Mrouana", "Sriana", "Mnaa", "Almadhr", "Tazoult", "Nkaous", "Aris", "Ain Djasr", "Skana", "Ichmoul", "Bouzina", "Alchmra", "Brika", "Aldjzar", "Tkout"],
  "Bdjaia": ["Sidi Aich", "Brbacha", "Alksr", "Khrata", "Bdjaia", "Bni Maouch", "Amizour", "Timzrit", "Souk Alithnin", "Tichi", "Ighil Ali", "Drkina", "Aoukas", "Adkar", "Akbou", "Sdouk", "Tazmlt", "Chmini", "Ifri Aouzlakn"],
  "Biskra": ["Zriba Alouadi", "Toulka", "Aourlal", "Djmoura", "Aloutaia", "Alkntra", "Bskra", "Foughala", "Sidi Akba", "Mchounch"],
  "Bechar": ["Bchar", "Lhmr", "Alknadsa", "Taghit", "Alabadla", "Bni Ounif", "Tblbala"],
  "Blida": ["Aoulad Iaich", "Boukra", "Mouzaia", "Alarbaa", "Boufarik", "Mftah", "Alafroun", "Ouadi Alalaik", "Bouainan", "Alblida"],
  "Bouira": ["Ain Bsam", "Brdj Aoukhris", "Sour Alghzlan", "Bchloul", "Mchd Allh", "Bir Ghbalou", "Albouira", "Souk Alkhmis", "Alkadria", "Alhachmia", "Alhizr", "Alakhdria"],
  "Tamanrasset": ["Tazrouk", "Silt", "Tmnrast"],
  "Tebessa": ["Alma Alabid", "Alaouinat", "Nkrin", "Bir Mkdm", "Mrst", "Am Ali", "Alkouif", "Alounza", "Alakla", "Alchriaa", "Bir Alaatr", "Tbsa"],
  "Tlemcen": ["Bab Alasa", "Mnsoura", "Chtouan", "Hnin", "Sidi Aldjilali", "Ndrouma", "Mrsa Bn Mhidi", "Bni Bousaid", "Sbdou", "Sbra", "Mghnia", "Alhnaia", "Bn Skran", "Flaousn", "Tlmsan", "Ain Talout", "Alrmchi", "Alghzouat", "Aoulad Mimoun", "Bni Snous"],
  "Tiaret": ["Mhdia", "Alsoukr", "Mghila", "Frnda", "Ain Krms", "Ksr Alchlala", "Rhouia", "Ouadi Lili", "Mchra Alsfa", "Hmadia", "Tiart", "Mdrousa", "Ain Aldhhb", "Dhmouni"],
  "Tizi Ouzou": ["Tikzirt", "Bouzkn", "Bni Douala", "Ouadia", "Azfoun", "Boughni", "Dhraa Bn Khda", "Ouasif", "Mkla", "Bni Ini", "Tizi Ouzou", "Ain Alhmam", "Makouda", "Dhraa Almizan", "Tizi Ghnif", "Ifrhounan", "Azazka", "Alarbaa Nath Iirathn", "Tizi Rachd", "Ouaknoun", "Maatka"],
  "Alger": ["Hsin Dai", "Braki", "Aldar Albida", "Bir Touta", "Alrouiba", "Zralda", "Aldraria", "Alchraka", "Sidi Amhmd", "Bir Mrad Rais", "Bab Alouadi", "Bouzriaa", "Alhrach"],
  "Djelfa": ["Hasi Bhbh", "Ain Alibl", "Alcharf", "Dar Alchioukh", "Hd Alshari", "Sidi Ladjal", "Msad", "Aladrisia", "Aldjlfa", "Birin", "Fid Albtma", "Ain Ousara"],
  "Jijel": ["Djidjl", "Alaouana", "Ziama Mnsouria", "Altahir", "Alchkfa", "Almilia", "Sidi Marouf", "Alstara", "Alansr", "Djimla", "Taksna"],
  "Setif": ["Salh Bai", "Amoucha", "Ain Arnat", "Ain Oulman", "Bouandas", "Hmam Alskhna", "Ain Azal", "Knzat", "Boukaaa", "Hmam Krkour", "Stif", "Ain Alkbira", "Bni Aziz", "Bir Alarch", "Maouklan", "Babour", "Kdjal", "Alalma", "Djmila", "Bni Ourtilan"],
  "Saida": ["Saida", "Aoulad Abrahim", "Alhsasna", "Sidi Boubkr", "Ioub", "Ain Alhdjr"],
  "Skikda": ["Sidi Mzghich", "Alhrouch", "Alhdaik", "Rmdan Djmal", "Tmalous", "Ain Kchra", "Am Altoub", "Azaba", "Alzitouna", "Aoulad Atia", "Alkl", "Bn Azouz", "Skikda"],
  "Sidi Bel Abbes": ["Sidi Ali Bn Ioub", "Moulai Slisn", "Tnira", "Mrin", "Sidi Lhsn", "Ain Albrd", "Bn Badis", "Sfizf", "Mrhoum", "Ras Alma", "Sidi Blabas", "Tsala", "Mstfa Bn Abrahim", "Tlagh", "Sidi Ali Bousidi"],
  "Annaba": ["Anaba", "Brhal", "Alhdjar", "Albouni", "Ain Albarda", "Chtaibi"],
  "Guelma": ["Klaa Bousba", "Hmam Dbagh", "Hmam Alnbail", "Kalma", "Bouchkouf", "Hiliouboulis", "Ain Hsainia", "Ouadi Alznati", "Ain Mkhlouf", "Khzara"],
  "Constantine": ["Hama Bouzian", "Zighoud Iousf", "Alkhroub", "Ain Abid", "Abn Ziad", "Ksntina"],
  "Medea": ["Aoulad Antr", "Alsouaki", "Ksr Albkhari", "Alazizia", "Alchhbounia", "Aouamri", "Bni Sliman", "Si Almhdjoub", "Albrouakia", "Sghouan", "Tablat", "Almdia", "Ouzra", "Ain Bousif", "Alamaria", "Alklb Alkbir", "Chlala Aladhaoura", "Sidi Naman", "Aziz"],
  "Mostaganem": ["Ain Nouisi", "Ain Tadls", "Hasi Mamach", "Khir Aldin", "Sidi Ali", "Sidi Lkhdr", "Mstghanm", "Achaacha", "Boukirat", "Masra"],
  "M'Sila": ["Chlal", "Mkra", "Sidi Aisa", "Ain Alhdjl", "Bousaada", "Aoulad Sidi Abrahim", "Sidi Aamr", "Bn Srour", "Ain Almlh", "Amdjdl", "Djbl Msaad", "Almsila", "Hmam Aldlaa", "Aoulad Dradj", "Khbana"],
  "Mascara": ["Ouadi Alabtal", "Almhmdia", "Tighnif", "Zhana", "Akaz", "Sik", "Ain Fars", "Bouhnifia", "Aouf", "Ouadi Altaghia", "Ain Fkan", "Albrdj", "Ghris", "Maskr", "Tizi", "Alhchm"],
  "Ouargla": ["Ourkla", "Hasi Msaoud", "Sidi Khouild", "Albrma", "Ankousa"],
  "Oran": ["Alsania", "Kdil", "Bir Aldjir", "Arziou", "Btioua", "Ain Altrk", "Ouhran", "Ouadi Tlilat", "Boutlilis"],
  "El Bayadh": ["Alabid Sidi Alchikh", "Brizina", "Boualam", "Bouktb", "Albid", "Rkasa", "Chlala", "Bousmghoun"],
  "Illizi": ["In Amnas", "Iilizi"],
  "Bordj Bou Arreridj": ["Alhmadia", "Almnsoura", "Ain Taghrout", "Brdj Alghdir", "Bir Kasd Ali", "Djaafra", "Mdjana", "Ras Alouadi", "Brdj Zmoura", "Brdj Bouariridj"],
  "Boumerdes": ["Boudouaou", "Dls", "Althnia", "Khmis Alkhchna", "Isr", "Brdj Mnail", "Alnasria", "Bghlia", "Boumrdas"],
  "El Tarf": ["Altarf", "Albsbas", "Bouhdjar", "Bn Mhidi", "Aldhraan", "Alkala", "Bouthldja"],
  "Tindouf": ["Tndouf"],
  "Tissemsilt": ["Khmisti", "Thnia Alahd", "Tismsilt", "Lrdjam", "Brdj Bounaama", "Amari", "Alazhria", "Brdj Alamir Abd Alkadr"],
  "El Oued": ["Altalb Alarbi", "Alrbah", "Almkrn", "Amih Ouansa", "Alouadi", "Albiada", "Kmar", "Alrkiba", "Aldbila", "Hasi Khlifa"],
  "Khenchela": ["Chchar", "Babar", "Aoulad Rchach", "Bouhmama", "Khnchla", "Kais", "Alhama", "Ain Altouila"],
  "Souk Ahras": ["Souk Ahras", "Sdrata", "Almchrouha", "Aoulad Idris", "Am Alazaim", "Mdaourouch", "Taoura", "Alhdada", "Almrahna", "Bir Bouhouch"],
  "Tipaza": ["Hdjout", "Sidi Aamr", "Kouraia", "Chrchal", "Aldamous", "Fouka", "Bouasmaail", "Ahmr Alain", "Alkliaa", "Tibaza"],
  "Mila": ["Altlaghma", "Ain Albida Ahrich", "Trai Bainan", "Tsdan Hdada", "Sidi Mrouan", "Alkrarm Kouka", "Alrouachd", "Bouhatm", "Ouadi Alndja", "Tadjnant", "Chlghoum Alaid", "Mila", "Frdjioua"],
  "Ain Defla": ["Khmis", "Hmam Righa", "Djlida", "Boumdfa", "Alaamra", "Alataf", "Alabadia", "Djndl", "Mliana", "Ain Alachiakh", "Alrouina", "Brdj Alamir Khald", "Bthia", "Ain Aldfla"],
  "Naama": ["Ain Alsfra", "Mghrar", "Asla", "Mkmn Bn Amar", "Almchria", "Alnaama", "Sfisifa"],
  "Ain Temouchent": ["Ain Alarbaa", "Almalh", "Hmam Bouhdjr", "Alaamria", "Ain Alkihl", "Bni Saf", "Oulhasa Alghraba", "Ain Tmouchnt"],
  "Ghardaia": ["Daia Bn Dhoua", "Almnsoura", "Bounoura", "Zlfana", "Alkrara", "Mtlili", "Brian", "Ghrdaia"],
  "Relizane": ["Mazouna", "Ami Mousa", "Zmoura", "Djdiouia", "Almtmr", "Ain Tark", "Ill", "Alrmka", "Mndas", "Ouadi Rhiou", "Ghlizan", "Sidi Amhmd Bn Ali", "Alhmadna"],
  "Timimoun": ["Tnrkouk", "Timimoun", "Aoukrout", "Chrouin"],
  "Bordj Badji Mokhtar": ["Brdj Badji Mkhtar"],
  "Ouled Djellal": ["Sidi  Khald", "Aoulad Djlal"],
  "Béni Abbès": ["Bni Abas", "Ikli", "Alouata", "Aoulad Khdir", "Krzaz"],
  "In Salah": ["Iinghr", "Ain Salh"],
  "In Guezzam": ["Tin Zouatin", "Ain Kzam"],
  "Touggourt": ["Tmasin", "Almkarin", "Tkrt", "Altibat", "Alhdjira"],
  "Djanet": ["Djant"],
  "El M'Ghair": ["Almghir", "Djamaa"],
  "El Meniaa": ["Almniaa", "Almnsoura"],
};