export const wilayas: Record<string, string[]> = {
  // Wilaya 01 - 10
  "Adrar": ["Adrar", "Aoulef", "Fenoughil", "Reggane", "Tsabit", "Zaouiet Kounta"],
  "Chlef": ["Chlef", "Abou El Hassan", "Aïn Merane", "Béni Haoua", "Boukadir", "El Karimia", "El Marsa", "Oued Fodda", "Ouled Ben Abdelkader", "Ouled Farès", "Taougrite", "Ténès", "Zeboudja"],
  "Laghouat": ["Laghouat", "Aflou", "Aïn Madhi", "Brida", "El Ghicha", "Gueltet Sidi Saâd", "Hassi R'Mel", "Ksar El Hirane", "Oued Morra", "Sidi Makhlouf"],
  "Oum El Bouaghi": ["Oum El Bouaghi", "Aïn Babouche", "Aïn Beïda", "Aïn Fakroun", "Aïn Kercha", "Aïn M'lila", "Dhalaa", "Fkirina", "Ksar Sbahi", "Meskiana", "Sigus", "Souk Naamane"],
  "Batna": ["Batna", "Aïn Djasser", "Aïn Touta", "Arris", "Barika", "Bouzina", "Chemora", "Djezzar", "El Madher", "Ichmoul", "Menaa", "Merouana", "N'Gaous", "Ouled Si Slimane", "Ras El Aioun", "Seggana", "Seriana", "T'Kout", "Tazoult", "Teniet El Abed", "Thimgad"],
  "Béjaïa": ["Béjaïa", "Adekar", "Akbou", "Amizour", "Aokas", "Barbacha", "Béni Maouche", "Chemini", "Darguina", "El Kseur", "Ifri-Ouzellaguen", "Ighil Ali", "Kherrata", "Ouzellaguen", "Seddouk", "Sidi Aïch", "Souk El Ténine", "Tazmalt", "Tichy"],
  "Biskra": ["Biskra", "Djemorah", "El Kantara", "El Outaya", "Foughala", "M'Chouneche", "Ourlal", "Sidi Okba", "Tolga", "Zeribet El Oued"],
  "Béchar": ["Béchar", "Abadla", "Beni Ounif", "Kenadsa", "Lahmar", "Taghit"],
  "Blida": ["Blida", "Boufarik", "Bougara", "Bouïnane", "El Affroun", "Larbaâ", "Meftah", "Mouzaïa", "Oued El Alleug", "Ouled Yaïch"],
  "Bouira": ["Bouira", "Aïn Bessem", "Bechloul", "Bir Ghbalou", "Bordj Okhriss", "El Hachimia", "Haizer", "Kadiria", "Lakhdaria", "M'Chedallah", "Souk El Khemis", "Sour El Ghozlane"],

  // Wilaya 11 - 20
  "Tamanrasset": ["Tamanrasset", "Abalessa", "Tazrouk"],
  "Tébessa": ["Tébessa", "Bir el-Ater", "Bir Mokkadem", "Cheria", "El Aouinet", "El Kouif", "El Ma Labiodh", "El Ogla", "Morsott", "Negrine", "Ouenza", "Oum Ali"],
  "Tlemcen": ["Tlemcen", "Aïn Talout", "Bab El Assa", "Béni Boussaïd", "Béni Snous", "Bensekrane", "Chetouane", "Fellaoucene", "Ghazaouet", "Hennaya", "Honaïne", "Maghnia", "Mansourah", "Marsa Ben M'Hidi", "Nedroma", "Ouled Mimoun", "Remchi", "Sabra", "Sebdou", "Sidi Djillali"],
  "Tiaret": ["Tiaret", "Aïn Deheb", "Aïn Kermes", "Dahmouni", "Frenda", "Hamadia", "Ksar Chellala", "Mahdia", "Mechraâ Sfa", "Medroussa", "Meghila", "Oued Lili", "Rahouia", "Sougueur"],
  "Tizi Ouzou": ["Tizi Ouzou", "Aïn El Hammam", "Azazga", "Azeffoun", "Beni Douala", "Beni Yenni", "Boghni", "Bouzguene", "Draâ Ben Khedda", "Draâ El Mizan", "Iferhounène", "Larbaâ Nath Irathen", "Mâatkas", "Makouda", "Mekla", "Ouacif", "Ouadhia", "Ouaguenoun", "Tigzirt", "Tizi Gheniff", "Tizi Rached"],
  "Alger": ["Alger", "Bab El Oued", "Baraki", "Bir Mourad Raïs", "Birtouta", "Bouzaréah", "Chéraga", "Dar El Beïda", "Draria", "El Harrach", "Hussein Dey", "Rouïba", "Sidi M'Hamed", "Zéralda"],
  "Djelfa": ["Djelfa", "Aïn El Ibel", "Aïn Oussera", "Birine", "Charef", "Dar Chioukh", "El Idrissia", "Faidh El Botma", "Had-Sahary", "Hassi Bahbah", "Messaâd", "Sidi Ladjel"],
  "Jijel": ["Jijel", "Aouana", "Chekfa", "Djimla", "El Ancer", "El Aouana", "El Milia", "Settara", "Sidi Marouf", "Taher", "Texenna", "Ziama Mansouriah"],
  "Sétif": ["Sétif", "Aïn Arnat", "Aïn Azel", "Aïn El Kebira", "Aïn Oulmene", "Amoucha", "Babor", "Beni Aziz", "Beni Ourtilane", "Bir El Arch", "Bouandas", "Bougaa", "Djemila", "El Eulma", "Guenzet", "Guidjel", "Hammam Guergour", "Hammam Soukhna", "Maoklane", "Salah Bey"],
  "Saïda": ["Saïda", "Aïn El Hadjar", "El Hassasna", "Ouled Brahim", "Sidi Boubekeur", "Youb"],

  // Wilaya 21 - 30
  "Skikda": ["Skikda", "Aïn Kechra", "Azzaba", "Ben Azzouz", "Collo", "El Harrouch", "El Hadaiek", "Ouled Attia", "Oum Toub", "Ramdane Djamel", "Sidi Mezghiche", "Tamalous", "Zitouna"],
  "Sidi Bel Abbès": ["Sidi Bel Abbès", "Aïn El Berd", "Ben Badis", "Marhoum", "Merine", "Mostefa Ben Brahim", "Moulay Slissen", "Ras El Ma", "Sfisef", "Sidi Ali Benyoub", "Sidi Ali Boussidi", "Sidi Lahcene", "Telagh", "Tenira", "Tessala"],
  "Annaba": ["Annaba", "Aïn Berda", "Berrahal", "Chetaïbi", "El Bouni", "El Hadjar"],
  "Guelma": ["Guelma", "Aïn Makhlouf", "Bouchegouf", "Guelaât Bou Sbaâ", "Hammam Debagh", "Hammam N'Bail", "Héliopolis", "Khezaras", "Oued Zenati", "Roknia"],
  "Constantine": ["Constantine", "Aïn Abid", "El Khroub", "Hamma Bouziane", "Ibn Ziad", "Zighoud Youcef"],
  "Médéa": ["Médéa", "Aïn Boucif", "Aziz", "Beni Slimane", "Berrouaghia", "Chahbounia", "Chellalet El Adhaoura", "El Azizia", "El Guelb El Kebir", "El Omaria", "Ksar Boukhari", "Ouamri", "Ouzera", "Seghouane", "Si Mahdjoub", "Sidi Naamane", "Souagui", "Tablat"],
  "Mostaganem": ["Mostaganem", "Achacha", "Aïn Nouïssy", "Aïn Tédelès", "Bouguirat", "Hassi Mameche", "Khadra", "Mascara", "Mesra", "Sidi Ali", "Sidi Lakhdar"],
  "M'Sila": ["M'Sila", "Aïn El Hadjel", "Aïn El Melh", "Ben Srour", "Bousaâda", "Chellal", "Djebel Messaâd", "Hammam Dhalaâ", "Khoubana", "Magra", "Medjedel", "Ouled Derradj", "Ouled Sidi Brahim", "Sidi Aïssa", "Sidi Ameur"],
  "Mascara": ["Mascara", "Aïn Fares", "Aïn Fekan", "Aouf", "Bou Hanifia", "El Bordj", "Ghriss", "Hachem", "Mahammadia", "Oggaz", "Oued Taria", "Sig", "Tighennif", "Tizi", "Zahana"],
  "Ouargla": ["Ouargla", "El Borma", "Hassi Messaoud", "N'Goussa", "Sidi Khouiled"],

  // Wilaya 31 - 40
  "Oran": ["Oran", "Aïn El Turk", "Arzew", "Bethioua", "Bir El Djir", "Boutlélis", "Es Sénia", "Gdyel", "Oued Tlélat"],
  "El Bayadh": ["El Bayadh", "Bouâlem", "Bougtob", "Boussemghoun", "Brezina", "Chellala", "El Abiodh Sidi Cheikh", "Rogassa"],
  "Illizi": ["Illizi", "In Amenas"],
  "Bordj Bou Arreridj": ["Bordj Bou Arreridj", "Aïn Taghrout", "Bir Kasdali", "Bordj Ghedir", "Bordj Zemoura", "Djaâfra", "El Hamadia", "Mansoura", "Medjana", "Ras El Oued"],
  "Boumerdès": ["Boumerdès", "Boudouaou", "Bordj Menaïel", "Dellys", "Isser", "Khemis El Khechna", "Naciria", "Thénia"],
  "El Tarf": ["El Tarf", "Besbes", "Bouhadjar", "Bouteldja", "Dréan", "El Kala", "Ben Mehidi"],
  "Tindouf": ["Tindouf"],
  "Tissemsilt": ["Tissemsilt", "Ammari", "Bordj Bounaâma", "Bordj Emir Abdelkader", "Khemisti", "Lardjem", "Lazharia", "Theniet El Had"],
  "El Oued": ["El Oued", "Debila", "Djamaa", "El M'Ghair", "Guemmar", "Hassi Khalifa", "Magrane", "Mih Ouansa", "Reguiba", "Robbah", "Taleb Larbi"],
  "Khenchela": ["Khenchela", "Aïn Touila", "Babar", "Bouhmama", "Chechar", "El Hamma", "Kaïs", "Ouled Rechache"],

  // Wilaya 41 - 48
  "Souk Ahras": ["Souk Ahras", "Bir Bouhouche", "Haddada", "M'Daourouch", "Mechrouha", "Merahna", "Ouled Driss", "Oum El Adhaim", "Sedrata", "Taoura"],
  "Tipaza": ["Tipaza", "Ahmer El Aïn", "Bou Ismaïl", "Cherchell", "Damous", "Fouka", "Gouraya", "Hadjout", "Koléa", "Sidi Amar"],
  "Mila": ["Mila", "Aïn Beida Harriche", "Bouhatem", "Chelghoum Laïd", "Ferdjioua", "Grarem Gouga", "Oued Endja", "Rouached", "Sidi Merouane", "Tadjnanet", "Tassadane Haddada", "Teleghma", "Terrai Bainen"],
  "Aïn Defla": ["Aïn Defla", "Aïn Lechiekh", "Bathia", "Bordj Emir Khaled", "Boumedfaa", "Djelida", "Djendel", "El Abadia", "El Amra", "El Attaf", "Hammam Righa", "Khemis Miliana", "Miliana", "Rouina"],
  "Naâma": ["Naâma", "Aïn Sefra", "Asla", "Makman Ben Amer", "Mécheria", "Moghrar", "Sfissifa"],
  "Aïn Témouchent": ["Aïn Témouchent", "Aïn El Arbaa", "Aïn Kihel", "Beni Saf", "El Amria", "El Malah", "Hammam Bou Hadjar", "Oulhaça El Gheraba"],
  "Ghardaïa": ["Ghardaïa", "Berriane", "Bounoura", "El Guerrara", "Metlili", "Zelfana", "Dhayet Bendhahoua"],
  "Relizane": ["Relizane", "Aïn Tarek", "Ammi Moussa", "Bendaoud", "Djidiouia", "El H'Madna", "El Matmar", "Mazouna", "Mendes", "Oued Rhiou", "Ramka", "Sidi M'Hamed Ben Ali", "Yellel", "Zemmoura"],

  // Wilaya 49 - 58 (New Wilayas)
  "Timimoun": ["Timimoun", "Aougrout", "Charouine", "Tinerkouk"],
  "Bordj Badji Mokhtar": ["Bordj Badji Mokhtar", "Timiaouine"],
  "Ouled Djellal": ["Ouled Djellal", "Sidi Khaled"],
  "Béni Abbès": ["Béni Abbès", "El Ouata", "Ighil", "Kerzaz", "Ouled Khodeir", "Tabelbala"],
  "In Salah": ["In Salah", "In Ghar"],
  "In Guezzam": ["In Guezzam", "Tin Zaouatine"],
  "Touggourt": ["Touggourt", "Blidet Amor", "El Hadjira", "Megarine", "Taïbet", "Temacine"],
  "Djanet": ["Djanet"],
  "El M'Ghair": ["El M'Ghair", "Djamaâ", "Oum Touyour", "Still"],
  "El Meniaa": ["El Meniaa", "Hassi Gara", "Mansoura"],
};